name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          cd "Images/Hello World/"
          docker build -t hello-world:1.0.0 .
          docker push ghcr.io/benhagaman/hello-world:1.0.0
          
# docker build . --file Dockerfile --tag my-image-name:$(date +%s)
