# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd "Images/Hello World/"
          docker build -t hello-world:1.0.0 .
          docker tag hello-world:1.0.0 ghcr.io/benhagaman/hello-world:1.0.0
          echo "TEST"
          echo "TEST"
          echo "TEST"
          echo "TEST"
          echo $GH_USERNAME
          # echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin
          docker push ghcr.io/benhagaman/hello-world:1.0.0


        
        #  cd "Images/Hello World/"
        #  docker build -t 1.0 .
